### PR TITLE
Add a cli option to fail if unused keys are found

### PR DESCRIPTION
**Pull request by LamaEats**
Add two flags
```sh
$ generate-i18n --quite --fail-if-unused
```

`-q, --quite` Disable logging by each locale file
`--fail-if-unused` Throws the error at least one file contains unused keys 

Resolve: #64

### CODE REVIEW

**Comment by LamaEats** [comment]
> Canary available: `easy-typed-intl@0.0.0-9969a92`

package bad name

**Review by awinogradov — CHANGES_REQUESTED** [review]

**Review by awinogradov — APPROVED** [review]

**Pull request merged**
